name: Java CI with Maven

on:
  push:
    branches: [ "main" ]   # Runs when you push to main
  pull_request:
    branches: [ "main" ]   # Runs on PRs to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build and test with Maven
      - name: Build with Maven
        run: mvn clean install

      # Step 4: Run tests
      - name: Run tests
        run: mvn test
